//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArlinaRamrattanM16_Lab3_Ex2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArlinaTB
    {
        public int learnerId { get; set; }
        public string learnerName { get; set; }
        public int learnerAge { get; set; }
        public string favMovie { get; set; }
        public string favDrink { get; set; }
    }
}
